<?php

use Drupal\pathauto\PathautoPatternInterface;
use Drupal\wmpathauto\Event\AliasAlterEvent;
use Drupal\wmpathauto\Event\PatternAlterEvent;

function wmpathauto_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context)
{
    \Drupal::getContainer()->get('event_dispatcher')->dispatch(
        PatternAlterEvent::NAME,
        new PatternAlterEvent($pattern, $context)
    );
}

function wmpathauto_pathauto_alias_alter(string &$alias, array $context)
{
    \Drupal::getContainer()->get('event_dispatcher')->dispatch(
        AliasAlterEvent::NAME,
        new AliasAlterEvent($alias, $context)
    );
}
